behaviors:
  GraduTest:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 256
      buffer_size: 2048
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.05
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 10000
    threaded: false
##behaviors:
##  GraduTest:
##    trainer_type: sac
##    max_steps: 1000000 #default: 500000
##    time_horizon: 32 #64
##    summary_freq: 10000 #50000
##    threaded: true #false    
##    hyperparameters:
##      batch_size: 32 #sac 32-512
##      buffer_size: 32000 #sac 50000
##      learning_rate: 0.0001 #0.0003
##      learning_rate_schedule: constant #sac constant
##      buffer_init_steps: 1000 #0
##      init_entcoef: 1 #discrete 0.05-0.5
##      save_replay_buffer: false #false
##      tau: 0.005 #0.005
##    network_settings:
##      normalize: false #false
##      hidden_units: 128 #128
##      num_layers: 2 #2
##      conditioning_type: hyper #hyper
##      ##vis_encode_type: simple
##      ##memory:
##      ##  memory_size: 128
##      ##  sequence_length: 64
##    reward_signals:
##      extrinsic:
##        gamma: 0.995
##        strength: 1.0
##behaviors:
##  GraduTest:
##    trainer_type: ppo
##    hyperparameters:
##      batch_size: 50
##      buffer_size: 500
##      learning_rate: 3.0e-4
##      beta: 5.0e-4
##      epsilon: 0.2
##      lambd: 0.99
##      num_epoch: 3
##      learning_rate_schedule: linear
##      ##beta_schedule: constant
##      ##epsilon_schedule: linear
##    network_settings:
##      normalize: false
##      hidden_units: 128
##      num_layers: 2
##    reward_signals:
##      extrinsic:
##        gamma: 0.99
##        strength: 1.0
##    max_steps: 1000000
##    time_horizon: 64
##    summary_freq: 10000